version: "3"

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./app/config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  redis: